name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9.13
  - requests=2.28.1
  - pip=22.2.2
  - mlflow=1.14.1
  - hydra-core=1.0.6
  - pip:
      - wandb==0.15.4
      - hydra-joblib-launcher==1.2.0
      - mlflow==2.4.1
